// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3u8wRbM-oIBjR6a4oK1q7vKe6krdmwgg',
    appId: '1:476846062600:web:aa04aa10faff5937e8a5bd',
    messagingSenderId: '476846062600',
    projectId: 'dietasdb',
    authDomain: 'dietasdb.firebaseapp.com',
    storageBucket: 'dietasdb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx52PMUK27GqoLosOe2KcbmcIkLDCX580',
    appId: '1:476846062600:android:2e93200370d2e4b0e8a5bd',
    messagingSenderId: '476846062600',
    projectId: 'dietasdb',
    storageBucket: 'dietasdb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXoEn7FlTXlPVYEhowyo5O4dAFURNcwko',
    appId: '1:476846062600:ios:1575640c091529bee8a5bd',
    messagingSenderId: '476846062600',
    projectId: 'dietasdb',
    storageBucket: 'dietasdb.firebasestorage.app',
    iosBundleId: 'com.example.appDietas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXoEn7FlTXlPVYEhowyo5O4dAFURNcwko',
    appId: '1:476846062600:ios:1575640c091529bee8a5bd',
    messagingSenderId: '476846062600',
    projectId: 'dietasdb',
    storageBucket: 'dietasdb.firebasestorage.app',
    iosBundleId: 'com.example.appDietas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3u8wRbM-oIBjR6a4oK1q7vKe6krdmwgg',
    appId: '1:476846062600:web:161d12102d1b699ee8a5bd',
    messagingSenderId: '476846062600',
    projectId: 'dietasdb',
    authDomain: 'dietasdb.firebaseapp.com',
    storageBucket: 'dietasdb.firebasestorage.app',
  );
}
